name: Update Auth Token
on:
  push:
    branches: [main]

jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Replace Auth Token
        run: |
          sed -i "s/AUTH_TOKEN/${{ secrets.AUTH_TOKEN }}/g" admin.html
      - name: Commit changes
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git commit -am "${{ secrets.AUTH_TOKEN }}"
          git push