name: Secrets
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sed -i "s/const AUTH_TOKEN = process.env.AUTH_TOKEN;/const AUTH_TOKEN = '${{ secrets.AUTH_TOKEN }}';/" admin.html