name: Build and Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sed -i "s/AUTH_TOKEN/${{ secrets.AUTH_TOKEN }}/g" admin.html
          echo "Replacement done. Checking result:"
          cat admin.html | tail -n 38
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: admin-html
          path: admin.html

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: admin-html
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Replace AUTH_TOKEN with actual token"
          git push