name: Update Auth Token and Deploy
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Auth Token
        run: |
          echo "Using AUTH_TOKEN: $AUTH_TOKEN"
          # Use $AUTH_TOKEN in your deployment scripts instead of modifying files
      - name: Deploy to GitHub Pages
        run:
          echo "Deploying to GitHub Pages with AUTH_TOKEN..."
