name: Secrets
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          echo "Maybe?"