name: Secrets
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          sed -i "s/AUTH_TOKEN/${{ secrets.AUTH_TOKEN }}/g" admin.html
          echo "Replacement done. Checking result:"
          grep AUTH_TOKEN admin.html          grep AUTH_TOKEN admin.html