name: Secrets
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        env:
          AUTH_TOKEN: ${{ secrets.AUTH_TOKEN }}
        run: |
          TOKEN_ESCAPED=$(printf '%s\n' "${{ secrets.AUTH_TOKEN }}" | sed -e 's/[\/&]/\\&/g')
          sed -i "s/AUTH_TOKEN/$TOKEN_ESCAPED/g" admin.html
