name: Update Auth Token and Deploy
on:
  push:
    branches: [main]

jobs:
  update-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}
      - name: Replace Auth Token
        run: |
          sed -i "s/AUTH_TOKEN/${{ secrets.AUTH_TOKEN }}/g" admin.html

  deploy:
    needs: update-token
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
